import {
  PUBLIC_FIREBASE_API_KEY,
  PUBLIC_FIREBASE_APP_ID,
  PUBLIC_FIREBASE_AUTH_DOMAIN,
  PUBLIC_FIREBASE_MEASUREMENT_ID,
  PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  PUBLIC_FIREBASE_PROJECT_ID,
  PUBLIC_FIREBASE_STORAGE_BUCKET,
  PUBLIC_USER_SERVICE_BASE_URL,
} from '$env/static/public';

export const env = {
  firebase: {
    apiKey: PUBLIC_FIREBASE_API_KEY,
    appId: PUBLIC_FIREBASE_APP_ID,
    authDomain: PUBLIC_FIREBASE_AUTH_DOMAIN,
    senderId: PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    projectId: PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: PUBLIC_FIREBASE_STORAGE_BUCKET,
    measurementId: PUBLIC_FIREBASE_MEASUREMENT_ID,
  },
  userServiceBaseUrl: PUBLIC_USER_SERVICE_BASE_URL,
};
