name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm ci

      - name: Extract version from package.json
        id: extract_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t bukiteasy/client:${{ github.sha }} .

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Docker image
        run: |
          IMAGE_TAG=${{ env.VERSION }}
          docker tag bukiteasy/client:${{ github.sha }} bukiteasy/client:$IMAGE_TAG
          docker push bukiteasy/client:$IMAGE_TAG

    outputs:
      VERSION: ${{ env.VERSION }}

  version:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ needs.build.outputs.VERSION }}
          release_name: Release ${{ needs.build.outputs.VERSION }}
          body: |
            Changes in this release:
            - Description of changes
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
